In [2]:
# Welcome to your new notebook
# Bronze Layer Ingestion for Sales Data

# Step 1: Read CSV from Lakehouse 'Files/raw/'
df_sales = spark.read.option("header", "true").csv("Files/raw/sales.csv")

# Step 2: Display schema and preview rows
df_sales.printSchema()
df_sales.show(5)

# Step 3: Clean minimal nulls
df_sales_clean = df_sales.dropna(subset=["Item", "Quantity", "UnitPrice"])

# Step 4: Write to Bronze Delta table
df_sales_clean.write.format("delta").mode("overwrite").save("Tables/Bronze_Sales")

print("Bronze Sales Table created successfully.")

StatementMeta(, c3e39ee9-18f6-4397-bef8-055342068f83, 4, Finished, Available, Finished)

root
 |-- SalesOrderNumber: string (nullable = true)
 |-- SalesOrderLineNumber: string (nullable = true)
 |-- OrderDate: string (nullable = true)
 |-- CustomerName: string (nullable = true)
 |-- EmailAddress: string (nullable = true)
 |-- Item: string (nullable = true)
 |-- Quantity: string (nullable = true)
 |-- UnitPrice: string (nullable = true)
 |-- TaxAmount: string (nullable = true)

+----------------+--------------------+----------+--------------+--------------------+--------------------+--------+---------+---------+
|SalesOrderNumber|SalesOrderLineNumber| OrderDate|  CustomerName|        EmailAddress|                Item|Quantity|UnitPrice|TaxAmount|
+----------------+--------------------+----------+--------------+--------------------+--------------------+--------+---------+---------+
|         SO43701|                   1|2019-07-01|   Christy Zhu|christy12@adventu...|Mountain-100 Silv...|       1|  3399.99| 271.9992|
|         SO43704|                   1|2019-07-01|    Julio Ruiz|julio1@adventure-...|Mountain-100 Blac...|       1|  3374.99| 269.9992|
|         SO43705|                   1|2019-07-01|     Curtis Lu|curtis9@adventure...|Mountain-100 Silv...|       1|  3399.99| 271.9992|
|         SO43700|                   1|2019-07-01|  Ruben Prasad|ruben10@adventure...|  Road-650 Black, 62|       1| 699.0982|  55.9279|
|         SO43703|                   1|2019-07-01|Albert Alvarez|albert7@adventure...|    Road-150 Red, 62|       1|  3578.27| 286.2616|
+----------------+--------------------+----------+--------------+--------------------+--------------------+--------+---------+---------+
only showing top 5 rows

Bronze Sales Table created successfully.